name: Generate Table of Contents

on:
  push:
    branches:
      - '*'

jobs:
  generate_toc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install markdown-toc
        run: npm install markdown-toc -g
      
      - name: Generate Table of Contents
        run: markdown-toc -i README.md
