name: Generate Table of Contents

on:
  push:
    branches:
      - '*'

jobs:
  generate_toc:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Table of Contents
      uses: michaeldfallen/markdown-toc@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
