name: Generate Table of Contents

on:
  push:
    branches:
      - '*'

jobs:
  generate_toc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install markdown-toc
        run: npm install markdown-toc -g
      
      - name: Generate Table of Contents
        run: |
          table_of_contents=$(markdown-toc -i README.md)
          echo "Generated Table of Contents:"
          echo "${table_of_contents}"
          echo "TABLE_OF_CONTENTS=${table_of_contents}" >> $GITHUB_ENV
